### PR TITLE
Update Asgardia.Constitution.Proposal.txt

### PR DESCRIPTION
**Pull request by ElweThor**
As promised, I reviewed your Constitutional draft and made my "comments" in terms of amendments: approve or refuse them at your will (they're mostly cosmetic, but something is took from my country's constitution, italian's one).

### CODE REVIEW

**Comment by ElweThor** [comment]
Have to learn how can I answer you, comment by comment (or, even better, how to see where in my text each comment is related).

**Comment by ElweThor** [comment]
"political opinions" is already encompassed earlier in the same sentence under "...there shall be no discrimination in political, economic,..."
ok, I thought it was better to re-specify: you know, sometimes Constitutions have to be "redundant" as, in a given place, there whould be all the composing "elements".
Anyway, feel free to expunge without problems.

**Comment by ElweThor** [comment]
_While I like that we could say "Asgard" years... Those "Asgard-years" have not been defined in scientific terms. By explicitly using Earth for the measure of time, we can be certain of the scientifically proven duration of what a "Earth-year" should be._
That was to emphasize the fact, despite all they told us, we **have** a calendar.
Secondarily, I was looking forward... let's say... 50-100 years in the future, when Asgardia should not be still tied to "Earth-" things: maybe we should refer to "Standard-<something>" where "Standard" and "Earth" are synonyms (like the way you did for "Basic" and "International English" (have to say I appreciated a lot).

**Comment by ElweThor** [comment]
_I'm not sure we need to express: "Everything which is not expressly forbidden is tacitly intended as allowed." Isn't this already implied?_

It was to leave a short sentence summarizing the whole concept. Even if it "should" be implied, better to write it explicitly IMHO.

**Comment by lorezyra** [comment]
For my comments above, try clicking on the _commented on **Asgardia.Constitution.Proposal.txt**_ link. It will take you directly to the line where I commented on.

**Comment by ElweThor** [comment]
_Under Article 8§5a, I have something similar without required notifications. This adds restrictions and becomes redundant._

As far as I can see, your art.8§5a refers the "basic principle" while my amendment details the way the people can exercise the right: for safety and security purposes, especially aboard a space colony or into a Moon/Martian settlement, authorities should be at least "notified". Keeping in mind they can't forbid people to assembly but, how can authorities keep people safe if, at the moment of the meeting, there is some danger?
I'm not joking with words, nor I like to place restrictions where they shouldn't be, but people's safety can be a concern (and authorities are even _responsible_ of safety).

**Comment by lorezyra** [comment]
Already patched based on the above in https://github.com/lorezyra/Asgardia.Government/commit/9fea09bea2ea1f33c54e2361e3d1566d26fb6d15

**Pull request closed without merging**
